version: "3.9"

services:

  postgres:
    image: postgis/postgis:16-3.4
    container_name: brreg-postgis

    restart: unless-stopped

    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: gisuser
      POSTGRES_PASSWORD: gispassword

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gisuser -d gis"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:

    image: dpage/pgadmin4

    container_name: brreg-pgadmin

    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: christoffer@ungdomslag.no
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "8080:80"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
